### Yes, you can call python

In [1]:
using PyCall

In [2]:
@pyimport matplotlib.pyplot as plt
x = linspace(0,2*pi,1000); y = sin(3*x + 4*cos(2*x));
plt.plot(x, y, color="red", linewidth=2.0, linestyle="--")
plt.show()

In [3]:
x

linspace(0.0,6.283185307179586,1000)

In [4]:
@pyimport scipy.optimize as so
opt = so.newton(x -> cos(x) - x, 1)

0.7390851332151607

In [5]:
opt

0.7390851332151607

### No, zero indexing is too convenient so it's not allowed

In [6]:
x[0]

LoadError: LoadError: BoundsError: attempt to access linspace(0.0,6.283185307179586,1000)
  at index [0]
while loading In[6], in expression starting on line 1

### You like Matlab? Great!

In [7]:
mat = [1 2 3; 4 5 6; 7 8 9]

3x3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [8]:
eig(mat)

([16.116843969807043,-1.1168439698070427,-1.3036777264747022e-15],
3x3 Array{Float64,2}:
 -0.231971  -0.78583     0.408248
 -0.525322  -0.0867513  -0.816497
 -0.818673   0.612328    0.408248)

In [9]:
mat1 = 1:9
reshape(mat1,3,3)

3x3 Array{Int64,2}:
 1  4  7
 2  5  8
 3  6  9

### Not Parallel? No Problem!

In [10]:
size = 4000
mat = rand(size,size);

In [15]:
blas_set_num_threads(1)
@time eig(mat);

108.553834 seconds (72.89 k allocations: 1.188 GB, 0.09% gc time)


In [16]:
blas_set_num_threads(4)
@time eig(mat);

 70.368240 seconds (72.89 k allocations: 1.188 GB, 0.14% gc time)


### Macros vs. Functions

In [17]:
macro sayhello()
   return :( println("Hello!") )
end

In [19]:
@sayhello

Hello!
